//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTechSearch
{
    using System;
    using System.Collections.Generic;
    
    public partial class computer
    {
        public int Id { get; set; }
        public string name { get; set; }
        public Nullable<double> old_price { get; set; }
        public Nullable<double> current_price { get; set; }
        public Nullable<double> savings { get; set; }
        public Nullable<double> processor { get; set; }
        public string os { get; set; }
        public string video_card { get; set; }
        public string hard_drive { get; set; }
        public byte[] memory { get; set; }
        public string screen { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string url { get; set; }
    }
}
