//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTechSearch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class computer
    {
        public int Id { get; set; }
        public string description { get; set; }
        public System.DateTime updated_at { get; set; }
        public int store_id { get; set; }
    
        public virtual store store { get; set; }
    }
}
